

name: CI


on:
  push:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"
  pull_request:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"


jobs:

  # Build & Test
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install
      - name: INSTALL
        uses: pnpm /action-setup@v2.0.1
        with:
          version: 16.0.0
          run_install: true

      # Build
      - name: BUILD
        run: yarn build

      # Upload dist artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/


