# .github/workflows/netlify.yml
name: Ci
on:
  push:
   paths-ignore:
     - ./github/**
     - .netlify
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name:  build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
        run:     yarn yarn build npx netlify --prod
